# Generated by Django 4.2.10 on 2024-03-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_accountstock_average_sell_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountstock',
            name='average_sell_cost',
        ),
    ]
